services:
  mysql:
    image: mysql:8.4
    container_name: campuslands-mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-campuslands_mysql}
      MYSQL_USER: ${MYSQL_USER:-campus}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-campus123}
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    container_name: campuslands-mysql-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "${PHPMYADMIN_PORT:-8085}:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
